### Show all products
GET https://www.aurapan.com/api/orders/products

### Show all my orders
GET http://ecommercemac.com/api/orders/myorders

### Show all orders
GET http://ecommercemac.com/api/orders

### Get the particular orders
GET http://ecommercemac.com/api/orders/1

### Create a order
POST http://ecommercemac.com/api/orders
Content-Type: application/json

{
  "cartItems": {
      "userId": "userId",
      "title": "product title",
      "qty": 1,
      "color": "white",
      "size": "M",
      "image": "./asset/sample.jpg",
      "price": 990,
      "countInStock": 3,
      "discount": 1,
      "productId": 1,
    },,
  "shippingAddress": {
    "address": "sunset villa",
    "city": "New York",
    "postalCode": "44205",
    "country": "USA",
  },
  "paymentMethod": "stripe"
}


### Mark the particulat order as delivered
PATCH http://ecommercemac.com/api/orders/1/deliver

### Cancel the particular order
PATCH http://ecommercemac.com/api/orders/1
