apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  # uncomment this if you want to run on docker desktop
  local:
    push: false
  # uncomment this if you want to run on google cloud platform
  # googleCloudBuild:
  #   projectId: aurapan-shop-367317
  artifacts:
    # uncomment this if you want to run on docker desktop
    - image: thasup/user
    # uncomment this if you want to run on google cloud platform
    # - image: us.gcr.io/aurapan-shop-367317/user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # uncomment this if you want to run on docker desktop
    - image: thasup/client
    # uncomment this if you want to run on google cloud platform
    # - image: us.gcr.io/aurapan-shop-367317/client
      context: client
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.css"
            dest: .
          - src: "**/*.jpg"
            dest: .
          - src: "**/*.png"
            dest: .
    # uncomment this if you want to run on docker desktop
    - image: thasup/product
    # uncomment this if you want to run on google cloud platform
    # - image: us.gcr.io/aurapan-shop-367317/product
      context: product
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # uncomment this if you want to run on docker desktop
    - image: thasup/order
    # uncomment this if you want to run on google cloud platform
    # - image: us.gcr.io/aurapan-shop-367317/order
      context: order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # uncomment this if you want to run on docker desktop
    - image: thasup/expiration
    # uncomment this if you want to run on google cloud platform
    # - image: us.gcr.io/aurapan-shop-367317/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # uncomment this if you want to run on docker desktop
    - image: thasup/payment
    # uncomment this if you want to run on google cloud platform
    # - image: us.gcr.io/aurapan-shop-367317/payment
      context: payment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
