apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: aurapan-shop-348908
  artifacts:
    # - image: thasup/user
    - image: us.gcr.io/aurapan-shop-348908/user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: thasup/client
    - image: us.gcr.io/aurapan-shop-348908/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.css"
            dest: .
          - src: "**/*.jpg"
            dest: .
          - src: "**/*.png"
            dest: .
    # - image: thasup/product
    - image: us.gcr.io/aurapan-shop-348908/product
      context: product
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: thasup/order
    - image: us.gcr.io/aurapan-shop-348908/order
      context: order
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: thasup/expiration
    - image: us.gcr.io/aurapan-shop-348908/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: thasup/payment
    - image: us.gcr.io/aurapan-shop-348908/payment
      context: payment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
