name: tests-payment

on:
  pull_request:
    paths:
      - "payment/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: payment/package-lock.json
      - run: npm ci
        working-directory: payment
      - run: npm run test:ci
        working-directory: payment
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
