name: tests-order

on:
  pull_request:
    paths:
      - "order/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: order/package-lock.json
      - run: npm ci
        working-directory: order
      - run: npm run test:ci
        working-directory: order
