name: tests-user

on:
  pull_request:
    paths:
      - "user/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: user/package-lock.json
      - run: npm ci
        working-directory: user
      - run: npm run test:ci
        working-directory: user
